name: Super-Linter

on:
  push:
jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Corrected syntax

      - name: Run Super-Linter
        uses: super-linter/super-linter@v5  # Corrected syntax
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
